server:
  port: 8100
  session:
    # 8小时过期
    timeout: 28800
spring:
  application:
    name: rebate
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/rebate?useUnicode=true&characterEncoding=UTF8&useSSL=false
      username: root
      password: 123456
      # 使用Hikari数据源
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    enabled: false
    cache: false
logging:
  level: debug
  path: ./log
---
spring:
  profiles: tmp
  datasource:
      url: jdbc:mysql://120.55.42.113:3306/rebate?useUnicode=true&characterEncoding=UTF8&useSSL=false
      username: root
      password: taxi123!@#
      # 使用Hikari数据源
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.jdbc.Driver
      ---
spring:
  profiles: prod
  datasource:
      url: jdbc:mysql://119.23.78.129:3306/rebate?useUnicode=true&characterEncoding=UTF8&useSSL=false
      username: root
      password: rebate123!@#
      # 使用Hikari数据源
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.jdbc.Driver
---
spring:
  profiles:
    active: dev
